"""icon_resolver.py -- deterministically snap a scene's 1-2 word icon CONCEPT to a
real staged Phosphor glyph name, or None when nothing clean fits.

The scene planner (prompts/scene_plan.md) emits a loose icon *concept* for a fact
chip -- e.g. "measurement", "sunlight", "yearly schedule", "cost". This resolver
maps that concept to an actual staged glyph basename
(frontend/public/icons/phosphor/regular/<name>.svg) using ONLY deterministic,
offline logic:

  1. exact staged-name match,
  2. a curated concept->glyph synonym map,
  3. a gated token-overlap fuzzy score over the glyph tag/category metadata in
     data/phosphor_index.json (generated by
     frontend/scripts/build-phosphor-index.mjs).

NO embeddings, NO API, no network -- fully deterministic. Guiding rule: prefer
None (the fact chip then renders text-only) over a confident-but-wrong icon, so
the confidence gate is tuned to that bias.

Not wired into the EDL / assembly / render pipeline yet -- callers resolve on
demand. See tools/icon_resolver_eval.py for the tuning harness.
"""
from __future__ import annotations

import json
import re
from pathlib import Path

# Index of staged glyphs -> {"tags": [...], "categories": [...]}. Loaded once at
# import via a __file__-relative path (backend/data/phosphor_index.json). The
# staged SVG set is authoritative: a name only appears here if its SVG ships, so
# the resolver can never return a glyph that isn't on disk.
_INDEX_PATH = Path(__file__).resolve().parent.parent / "data" / "phosphor_index.json"

try:
    with _INDEX_PATH.open("r") as _f:
        _INDEX: dict[str, dict] = json.load(_f)
except FileNotFoundError:  # index not generated yet -> resolve to None, never crash
    _INDEX = {}

# Confidence gate -- tuned against tools/icon_resolver_eval.py output. Raise to be
# stricter (more None); lower to resolve more concepts. The bias is toward None.
#
# MIN_SCORE=4 was chosen over the seed 3 after inspecting real output: a tag-only
# single-token match tops out at 3 (tag +2, coverage +1, no name hit) and produced
# confident-but-WRONG picks -- e.g. "roots" -> the "radical" (square-root) glyph,
# "secret" -> "detective". Requiring 4 gates those to None (text-only) while still
# accepting partial NAME-token matches (concept word is a token of a longer glyph
# name: "container" -> shipping-container, "music" -> music-note = 3 name + 1
# coverage) and multi-signal tag matches. The curated synonym map -- not fuzzy --
# is what carries the common callout concepts, so this only prunes weak guesses.
MIN_SCORE = 4   # minimum fuzzy score for the top candidate to be accepted
MIN_MARGIN = 1  # required lead over the runner-up (unless the top has a name hit)

# Dropped from concept token sets (never from glyph names, which are exact keys).
_STOPWORDS = {"of", "a", "an", "the", "for", "to", "and", "with", "in", "on"}


def _singularize(tok: str) -> str:
    """Tiny, safe plural->singular so "seeds"/"seed", "dates"/"date" unify. Applied
    to BOTH concept tokens and glyph name/tag/category tokens."""
    if len(tok) <= 3:
        return tok
    if tok.endswith("ies"):
        return tok[:-3] + "y"           # batteries -> battery
    for suf in ("ches", "shes", "ses", "xes", "zes"):
        if tok.endswith(suf):
            return tok[:-2]             # boxes -> box, dishes -> dish
    if tok.endswith("s") and not tok.endswith("ss"):
        return tok[:-1]                 # seeds -> seed  (grass stays grass)
    return tok


def _kebab(text: str) -> str:
    """Lowercase kebab-case of a phrase (non-alphanumeric runs -> single dash)."""
    return re.sub(r"[^a-z0-9]+", "-", text.lower()).strip("-")


def _norm_key(text: str) -> str:
    """Kebab a phrase AND singularize each part -- the canonical form both synonym
    keys and lookup candidates are stored in, so "seasons"->"season" aligns."""
    parts = [p for p in _kebab(text).split("-") if p]
    return "-".join(_singularize(p) for p in parts)


def _concept_tokens(norm: str) -> list[str]:
    """Ordered, deduped significant tokens of a concept: split on non-alphanumeric,
    drop stopwords, singularize."""
    out: list[str] = []
    seen: set[str] = set()
    for raw in re.split(r"[^a-z0-9]+", norm.lower()):
        if not raw or raw in _STOPWORDS:
            continue
        s = _singularize(raw)
        if not s or s in _STOPWORDS or s in seen:
            continue
        seen.add(s)
        out.append(s)
    return out


def _entry_tokens(name: str, meta: dict) -> tuple[set[str], set[str], set[str]]:
    """Singularized token sets for one glyph: (name, tags, categories)."""
    def toks(text: str) -> set[str]:
        return {_singularize(t) for t in re.split(r"[^a-z0-9]+", text.lower()) if t}

    name_tokens = toks(name)
    tag_tokens: set[str] = set()
    for tag in meta.get("tags", []):
        tag_tokens |= toks(tag)
    cat_tokens: set[str] = set()
    for cat in meta.get("categories", []):
        cat_tokens |= toks(cat)
    return name_tokens, tag_tokens, cat_tokens


# Precompute glyph token sets once at import (small, ~1500 entries).
_ENTRY_TOKENS: dict[str, tuple[set[str], set[str], set[str]]] = {
    name: _entry_tokens(name, meta) for name, meta in _INDEX.items()
}

# Curated concept -> canonical staged glyph. Grouped by target for auditability;
# keys are whitespace-separated. Every target is validated against _INDEX at
# lookup time, so a target missing from the staged set is skipped (never
# returned). Multi-word keys use hyphens ("full-sun", "how-long").
_SYNONYM_GROUPS = [
    ("ruler", "measurement measure depth spacing size length distance width diameter dimensions"),
    ("sun", "sun sunlight sunshine sunny daylight full-sun sun-exposure brightness"),
    ("cloud", "shade partial-shade"),
    ("calendar-dots", "schedule yearly annual every-year timeline dates recurring seasonal seasons"),
    ("clock", "time duration wait how-long timing"),
    ("timer", "countdown deadline timer"),
    ("hourglass", "patience long-term aging"),
    ("drop", "water watering moisture hydration humidity liquid"),
    ("thermometer", "temperature heat degrees warmth climate"),
    ("warning", "warning caution danger careful avoid risk hazard alert mistake"),
    ("hash", "count quantity number amount how-many tally"),
    ("list-numbers", "steps order numbered"),
    ("list-checks", "checklist todo tasks"),
    ("map-pin", "location place where position spot site"),
    ("map-trifold", "map area territory"),
    ("fork-knife", "food eat meal edible dining"),
    ("wrench", "tool tools equipment"),
    ("shovel", "dig digging"),
    ("scissors", "cut prune pruning trim snip"),
    ("coins", "money cost price cheap budget affordable savings value expense"),
    ("money", "cash dollars"),
    ("cloud-sun", "weather forecast"),
    ("wind", "wind windy breeze airflow air"),
    ("cloud-rain", "rain rainy storm stormy"),
    ("snowflake", "snow frost freezing"),
    ("lightning", "speed fast quick power energy electricity"),
    ("flame", "fire flame burning"),
    ("plant", "growth grow plant planting sprout seedling"),
    ("leaf", "leaf foliage greenery"),
    ("tree", "tree shrub"),
    ("check-circle", "check done correct success verified complete tip"),
    ("star", "star best favorite rating quality top"),
    ("heart", "love health wellness healthy"),
    ("target", "target goal aim precision accuracy focus"),
    ("arrows-out", "expand spread wider apart increase"),
    ("arrows-in", "shrink closer together decrease"),
    ("clock-clockwise", "repeat cycle again rotation reuse"),
    ("mountains", "mountain hill elevation terrain outdoors"),
]

_SYNONYMS: dict[str, str] = {}
for _target, _keys in _SYNONYM_GROUPS:
    for _k in _keys.split():
        _SYNONYMS[_norm_key(_k)] = _target


def _fuzzy(ctokens: list[str]) -> tuple[str | None, int]:
    """Token-overlap fuzzy match over all glyphs. Returns (name|None, top_score).

    Per concept token, award the MAX of +3 (name token) / +2 (tag) / +1 (category);
    +1 coverage bonus if every concept token landed somewhere. Rank by score, then
    more name hits, then shorter name, then lexicographic. Accept the top only if
    it clears the confidence gate; else None.
    """
    n = len(ctokens)
    if n == 0:
        return None, 0
    results: list[tuple[int, int, str]] = []
    for name, (name_tokens, tag_tokens, cat_tokens) in _ENTRY_TOKENS.items():
        score = 0
        name_hits = 0
        matched = 0
        for ct in ctokens:
            if ct in name_tokens:
                score += 3
                name_hits += 1
                matched += 1
            elif ct in tag_tokens:
                score += 2
                matched += 1
            elif ct in cat_tokens:
                score += 1
                matched += 1
        if matched == n:
            score += 1  # coverage: every concept token found a home
        if score > 0:
            results.append((score, name_hits, name))
    if not results:
        return None, 0
    # score desc, name_hits desc, name length asc, name lexicographic asc.
    results.sort(key=lambda r: (-r[0], -r[1], len(r[2]), r[2]))
    top_score, top_name_hits, top_name = results[0]
    runner_score = results[1][0] if len(results) > 1 else 0
    if top_score < MIN_SCORE:
        return None, top_score
    if (top_score - runner_score) >= MIN_MARGIN or top_name_hits >= 1:
        return top_name, top_score
    return None, top_score


def resolve_icon_verbose(concept: str) -> dict:
    """Resolve + expose HOW (for tools/eval). Returns
    {"icon": str|None, "score": int|None, "decision": "exact"|"synonym"|"fuzzy"|"none"}.
    """
    if not isinstance(concept, str):
        return {"icon": None, "score": None, "decision": "none"}
    norm = re.sub(r"\s+", " ", concept.strip().lower())
    if not norm:
        return {"icon": None, "score": None, "decision": "none"}

    # 1. Exact staged-name match (raw kebab -- keep plural glyph names like
    #    "arrows-out"/"coins" intact; do NOT singularize here).
    kebab = _kebab(norm)
    if kebab in _INDEX:
        return {"icon": kebab, "score": None, "decision": "exact"}

    ctokens = _concept_tokens(norm)

    # 2. Curated synonym: whole (normalized) phrase, then adjacent bigrams, then
    #    each token. First hit whose target is a real staged glyph wins.
    candidates = [_norm_key(norm)]
    candidates += [f"{ctokens[i]}-{ctokens[i + 1]}" for i in range(len(ctokens) - 1)]
    candidates += ctokens
    for cand in candidates:
        target = _SYNONYMS.get(cand)
        if target and target in _INDEX:
            return {"icon": target, "score": None, "decision": "synonym"}

    # 3. Gated fuzzy over tags/categories.
    name, score = _fuzzy(ctokens)
    if name and name in _INDEX:
        return {"icon": name, "score": score, "decision": "fuzzy"}
    return {"icon": None, "score": score, "decision": "none"}


def resolve_icon(concept: str) -> str | None:
    """Snap an icon CONCEPT to a staged Phosphor glyph name, or None if nothing
    clean fits. See module docstring for the algorithm."""
    return resolve_icon_verbose(concept)["icon"]
